
def my_custom_exception():
    pass